projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        dev1:
          url: http://localhost:3000/graphql

  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: src/db/prisma.yml
